### ISSUE TITLE
is it possible to upload a file in raw binary codec and not dag-pb?

### ISSUE THREAD

**Issue by sirpy** [web3-storage/w3cli#76]
is it possible to upload a file in raw binary codec and not dag-pb?

**Comment by alanshaw** [comment]
If the file is less than the block size (~1MB) then you _should_ get an IPLD raw codec in the CID (shout if not). If it's larger then I think you _have_ to receive a `dag-pb` for it to be "unixfs" and interpreted as such on a gateway for example.

**Comment by sirpy** [comment]
@alanshaw from my recollection I was trying to save a small json file and the codec was still dag-pb

**Comment by alanshaw** [comment]
Possibly because it's being wrapped by a directory by default?

You can use `--no-wrap` to not add it to a directory...but you lose the file name:

```console
$ echo 'smol' > smol.txt 
$ w3 up smol.txt --no-wrap
  1 file 5B
⁂ Stored 1 file
⁂ https://w3s.link/ipfs/bafkreifxrit63zljmzdyclnfhqjhhnh4atpanl7jc2mvusdsr2xqfejh3e
```

Note that even if it is wrapped with a directory, the file does have a raw codec, e.g.

```console
$ w3 up smol.txt          
  1 file 5B
⁂ Stored 1 file
⁂ https://w3s.link/ipfs/bafybeiakwn73d56c4eiuka32ud4dyi6rskf2rl5dwxgfuhvy3lr6ud6jjm
```

`bafybeiakwn73d56c4eiuka32ud4dyi6rskf2rl5dwxgfuhvy3lr6ud6jjm` is not raw, but is the CID of the directory, if you navigate to `https://w3s.link/ipfs/bafybeiakwn73d56c4eiuka32ud4dyi6rskf2rl5dwxgfuhvy3lr6ud6jjm/smol.txt` you can inspect the etag to see that the file CID is using the raw codec:

![Image](https://github.com/web3-storage/w3cli/assets/152863/fa236aac-ce3a-4f07-b6b6-a1ac2b1912e2)
